/****************************************************************************/
/****************************************************************************/
/************************* NAME     : Mohamed Hosni *************************/
/************************* DATE     : 10/2/2024      ************************/
/************************* SWC      : TIMERS        *************************/
/************************* VERSION  : 3.0           *************************/
/****************************************************************************/
/****************************************************************************/
#ifndef TIMERS_PROGRAM_C_
#define TIMERS_PROGRAM_C_



#include "Std_types.h"
#include "Bit_utils.h"


#include "TIMERS_interface.h"
#include "TIMERS_register.h"
#include "TIMERS_private.h"
#include "TIMERS_config.h"



/***********************************Global Pointers to Function **************************************/
static void  (*TIMERS_pfTimer0OVF)(void) = NULL;
static void  (*TIMERS_pfTimer0CTC)(void) = NULL;
/*****************************************************************************************************/
/******************************** Timer 0 Functions **************************************************/
/*****************************************************************************************************/

void TIMERS_voidTimer0Init (void)
{
	                /*Select TIMER0 mode */
	
	#if           TIMER0_MODE == NORMAL_MODE
	                /* Normal mode  */
	CLR_BIT (TIMERS_U8_TCCR0_REG,TIMERS_TCCR0_WGM01);
	CLR_BIT (TIMERS_U8_TCCR0_REG,TIMERS_TCCR0_WGM00);
	

	#elif         TIMER0_MODE == PWM_PHASE_CORRECT_MODE
	                /* PWM, Phase Correct  mode  */
	SET_BIT (TIMERS_U8_TCCR0_REG,TIMERS_TCCR0_WGM00);
	CLR_BIT (TIMERS_U8_TCCR0_REG,TIMERS_TCCR0_WGM01);
				/*Select Fast PWM Mode*/
								/*Normal Mode*/
			#if              TIMER0_PHASE_CORRECT_PWM_MODE == TIMER0_PHASE_PWM_DISCONNECTED

					  CLR_BIT (TIMERS_U8_TCCR0_REG , TIMERS_TCCR0_COM00);
					  CLR_BIT (TIMERS_U8_TCCR0_REG , TIMERS_TCCR0_COM01);

								 /*Non-Inverting Mode Mode*/
			#elif             TIMER0_PHASE_CORRECT_PWM_MODE == TIMER0_PHASE_PWM_NON_INVERTING_MODE

					  CLR_BIT (TIMERS_U8_TCCR0_REG , TIMERS_TCCR0_COM00);
					  SET_BIT (TIMERS_U8_TCCR0_REG , TIMERS_TCCR0_COM01);

							  /*Inverting Mode Mode*/
			#elif             TIMER0_PHASE_CORRECT_PWM_MODE == TIMER0_PHASE_PWM_INVERTING_MODE

					  SET_BIT (TIMERS_U8_TCCR0_REG , TIMERS_TCCR0_COM00);
					  SET_BIT (TIMERS_U8_TCCR0_REG , TIMERS_TCCR0_COM01);
			#endif
	
	#elif         TIMER0_MODE == CTC_MODE
					/* Clear ON Compare match mode  */
	CLR_BIT (TIMERS_U8_TCCR0_REG,TIMERS_TCCR0_WGM00);
	SET_BIT (TIMERS_U8_TCCR0_REG,TIMERS_TCCR0_WGM01);
	
	#elif         TIMER0_MODE == FAST_PWM_MODE
	             /*Fast PWM mode*/
	SET_BIT (TIMERS_U8_TCCR0_REG,TIMERS_TCCR0_WGM00);
	SET_BIT (TIMERS_U8_TCCR0_REG,TIMERS_TCCR0_WGM01);

				/*Set Compare match unit register*/
	TIMERS_U8_OCR0_REG = TIMER0_CTC_VALUE;
				/*Select Fast PWM Mode*/
								/*Normal Mode*/
			#if             TIMER0_FPWM_MODE == TIMER0_FPWM_DISCONNECTED

	                  CLR_BIT (TIMERS_U8_TCCR0_REG , TIMERS_TCCR0_COM00);
	                  CLR_BIT (TIMERS_U8_TCCR0_REG , TIMERS_TCCR0_COM01);

	                  	  	  	 /*Non-Inverting Mode Mode*/
			#elif             TIMER0_FPWM_MODE == TIMER0_FPWM_NON_INVERTING_MODE

	                  CLR_BIT (TIMERS_U8_TCCR0_REG , TIMERS_TCCR0_COM00);
	                  SET_BIT (TIMERS_U8_TCCR0_REG , TIMERS_TCCR0_COM01);

	                  	  	  /*Inverting Mode Mode*/
			#elif             TIMER0_FPWM_MODE == TIMER0_FPWM_INVERTING_MODE

	                  SET_BIT (TIMERS_U8_TCCR0_REG , TIMERS_TCCR0_COM00);
	                  SET_BIT (TIMERS_U8_TCCR0_REG , TIMERS_TCCR0_COM01);
			#endif
	#endif 
	
                     	/*Over Flow interrupt*/
#if              TIMERE0_OVERFLOW_STATE == ENABLE_OVERFLOW_INTERRUPT
		/*Set preLoad value*/
	TIMERS_U8_TCNT0_REG = TIMER0_PRELOAD;
	    /*Enable OVF Interrupt*/
	SET_BIT(TIMERS_U8_TIMSK_REG,TIMERS_TIMSK_TOIE0);
	
#elif            TIMERE0_OVERFLOW_STATE == DISABLE_OVERFLOW_INTERRUPT

	CLR_BIT(TIMERS_U8_TIMSK_REG,TIMERS_TIMSK_TOIE0);

#endif



                          /*CTC interrupt*/
#if                  TIMER0_CTC_INTERRUPT_STATE == ENABLE_CTC_INTERRUPT

		/*Set Compare match unit register*/
	TIMERS_U8_OCR0_REG = TIMER0_CTC_VALUE;
        /*Enable CTC Interrupt*/
    SET_BIT(TIMERS_U8_TIMSK_REG,TIMERS_TIMSK_OCIE0);

#elif            TIMER0_CTC_INTERRUPT_STATE == DISABLE_CTC_INTERRUPT
    CLR_BIT(TIMERS_U8_TIMSK_REG,TIMERS_TIMSK_OCIE0);
#endif


                   /*Set Non-PWM Mode*/
#if                  TIMER0_MODE == NORMAL_MODE

    	#if          TIMER0_CTC_MODE == CTC_NORMAL_MODE

			CLR_BIT (TIMERS_U8_TCCR0_REG , TIMERS_TCCR0_COM00);
			CLR_BIT (TIMERS_U8_TCCR0_REG , TIMERS_TCCR0_COM01);


		#elif        TIMER0_CTC_MODE == CTC_TOGGLE_MODE

			SET_BIT (TIMERS_U8_TCCR0_REG , TIMERS_TCCR0_COM00);
			CLR_BIT (TIMERS_U8_TCCR0_REG , TIMERS_TCCR0_COM01);

		#elif        TIMER0_CTC_MODE == CTC_CLEAR_MODE

			CLR_BIT (TIMERS_U8_TCCR0_REG , TIMERS_TCCR0_COM00);
			SET_BIT (TIMERS_U8_TCCR0_REG , TIMERS_TCCR0_COM01);

		#elif        TIMER0_CTC_MODE == CTC_SET_MODE

			SET_BIT (TIMERS_U8_TCCR0_REG , TIMERS_TCCR0_COM00);
			SET_BIT (TIMERS_U8_TCCR0_REG , TIMERS_TCCR0_COM01);
		#endif


#elif                TIMER0_MODE == CTC_MODE

		#if          TIMER0_CTC_MODE == CTC_NORMAL_MODE

			CLR_BIT (TIMERS_U8_TCCR0_REG , TIMERS_TCCR0_COM00);
			CLR_BIT (TIMERS_U8_TCCR0_REG , TIMERS_TCCR0_COM01);


		#elif        TIMER0_CTC_MODE == CTC_TOGGLE_MODE

			SET_BIT (TIMERS_U8_TCCR0_REG , TIMERS_TCCR0_COM00);
			CLR_BIT (TIMERS_U8_TCCR0_REG , TIMERS_TCCR0_COM01);

		#elif        TIMER0_CTC_MODE == CTC_CLEAR_MODE

			CLR_BIT (TIMERS_U8_TCCR0_REG , TIMERS_TCCR0_COM00);
			SET_BIT (TIMERS_U8_TCCR0_REG , TIMERS_TCCR0_COM01);

		#elif        TIMER0_CTC_MODE == CTC_SET_MODE

			SET_BIT (TIMERS_U8_TCCR0_REG , TIMERS_TCCR0_COM00);
			SET_BIT (TIMERS_U8_TCCR0_REG , TIMERS_TCCR0_COM01);
		#endif

#endif


                          /*Set preScaler*/
#if                  TIMER0_PRESCALER_MODE  == TIMER_OFF

	CLR_BIT (TIMERS_U8_TCCR0_REG,TIMERS_TCCR0_CS00);
	CLR_BIT (TIMERS_U8_TCCR0_REG,TIMERS_TCCR0_CS01);
	CLR_BIT (TIMERS_U8_TCCR0_REG,TIMERS_TCCR0_CS02);

#elif                TIMER0_PRESCALER_MODE  == DIVIDED_BY_1

	SET_BIT (TIMERS_U8_TCCR0_REG,TIMERS_TCCR0_CS00);
	CLR_BIT (TIMERS_U8_TCCR0_REG,TIMERS_TCCR0_CS01);
	CLR_BIT (TIMERS_U8_TCCR0_REG,TIMERS_TCCR0_CS02);

#elif                TIMER0_PRESCALER_MODE  == DIVIDED_BY_8

	CLR_BIT (TIMERS_U8_TCCR0_REG,TIMERS_TCCR0_CS00);
	SET_BIT (TIMERS_U8_TCCR0_REG,TIMERS_TCCR0_CS01);
	CLR_BIT (TIMERS_U8_TCCR0_REG,TIMERS_TCCR0_CS02);

#elif                TIMER0_PRESCALER_MODE  == DIVIDED_BY_64

	SET_BIT (TIMERS_U8_TCCR0_REG,TIMERS_TCCR0_CS00);
	SET_BIT (TIMERS_U8_TCCR0_REG,TIMERS_TCCR0_CS01);
	CLR_BIT (TIMERS_U8_TCCR0_REG,TIMERS_TCCR0_CS02);

#elif                TIMER0_PRESCALER_MODE  == DIVIDED_BY_256

	CLR_BIT (TIMERS_U8_TCCR0_REG,TIMERS_TCCR0_CS00);
	CLR_BIT (TIMERS_U8_TCCR0_REG,TIMERS_TCCR0_CS01);
	SET_BIT (TIMERS_U8_TCCR0_REG,TIMERS_TCCR0_CS02);


#elif                TIMER0_PRESCALER_MODE  == DIVIDED_BY_1024

	SET_BIT (TIMERS_U8_TCCR0_REG,TIMERS_TCCR0_CS00);
	CLR_BIT (TIMERS_U8_TCCR0_REG,TIMERS_TCCR0_CS01);
	SET_BIT (TIMERS_U8_TCCR0_REG,TIMERS_TCCR0_CS02);

#elif                TIMER0_PRESCALER_MODE  == TO_FALLING

	CLR_BIT (TIMERS_U8_TCCR0_REG,TIMERS_TCCR0_CS00);
	SET_BIT (TIMERS_U8_TCCR0_REG,TIMERS_TCCR0_CS01);
	SET_BIT (TIMERS_U8_TCCR0_REG,TIMERS_TCCR0_CS02);

#elif                TIMER0_PRESCALER_MODE  == TO_RISING

	SET_BIT (TIMERS_U8_TCCR0_REG,TIMERS_TCCR0_CS00);
	SET_BIT (TIMERS_U8_TCCR0_REG,TIMERS_TCCR0_CS01);
	SET_BIT (TIMERS_U8_TCCR0_REG,TIMERS_TCCR0_CS02);

#endif
}

u8 TIMERS_u8Timer0OVFSetCallBack (void (*Copy_pf)(void))
{
	u8 Local_u8ErrorState = OK;
	if (Copy_pf != NULL)
	{
		TIMERS_pfTimer0OVF = Copy_pf ;
	}
	else
	{
		Local_u8ErrorState=NOK;
	}
	return Local_u8ErrorState;
}

u8 TIMERS_u8Timer0CTCSetCallBack (void (*Copy_pf)(void))
{
	u8 Local_u8ErrorState = OK;
	if (Copy_pf != NULL)
	{
		TIMERS_pfTimer0CTC = Copy_pf ;
	}
	else
	{
		Local_u8ErrorState=NOK;
	}
	return Local_u8ErrorState;
}

void TIMERS_u8Timer0SetCompareMatchValue (u8 Copy_u8OCR0Value)
{
	TIMERS_U8_OCR0_REG = Copy_u8OCR0Value;
}

/*****************************************************************************************************/
/*****************************************************************************************************/

/*****************************************************************************************************/
/******************************** Timer 1 Functions **************************************************/
/*****************************************************************************************************/
void TIMERS_voidTimer1Init (void)
{
					/*Select Timer 1 Mode*/
#if                  TIMER1_MODE == NORMAL__0XFFFF_IM_MAX

	CLR_BIT(TIMERS_U8_TCCR1B_REG,TIMERS_TCCR1B_WGM13);
	CLR_BIT(TIMERS_U8_TCCR1B_REG,TIMERS_TCCR1B_WGM12);
	CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_WGM11);
	CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_WGM10);

#elif                TIMER1_MODE == PWM_PC_8_BIT_0X00FF_TOP_BOTTOM

	CLR_BIT(TIMERS_U8_TCCR1B_REG,TIMERS_TCCR1B_WGM13);
	CLR_BIT(TIMERS_U8_TCCR1B_REG,TIMERS_TCCR1B_WGM12);
	CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_WGM11);
	SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_WGM10);

#elif                TIMER1_MODE == PWM_PC_9_BIT_0X01FF_TOP_BOTTOM

	CLR_BIT(TIMERS_U8_TCCR1B_REG,TIMERS_TCCR1B_WGM13);
	CLR_BIT(TIMERS_U8_TCCR1B_REG,TIMERS_TCCR1B_WGM12);
	SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_WGM11);
	CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_WGM10);

#elif                TIMER1_MODE == PWM_PC_10_BIT_0X03FF_TOP_BOTTOM

	CLR_BIT(TIMERS_U8_TCCR1B_REG,TIMERS_TCCR1B_WGM13);
	CLR_BIT(TIMERS_U8_TCCR1B_REG,TIMERS_TCCR1B_WGM12);
	SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_WGM11);
	SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_WGM10);

#elif                TIMER1_MODE == CTC_OCR1A_IM_MAX

	CLR_BIT(TIMERS_U8_TCCR1B_REG,TIMERS_TCCR1B_WGM13);
	SET_BIT(TIMERS_U8_TCCR1B_REG,TIMERS_TCCR1B_WGM12);
	CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_WGM11);
	CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_WGM10);

#elif                TIMER1_MODE == FPWM_8_BIT_0X00FF_TOP_TOP

	CLR_BIT(TIMERS_U8_TCCR1B_REG,TIMERS_TCCR1B_WGM13);
	SET_BIT(TIMERS_U8_TCCR1B_REG,TIMERS_TCCR1B_WGM12);
	CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_WGM11);
	SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_WGM10);

#elif                TIMER1_MODE == FPWM_9_BIT_0X01FF_TOP_TOP

	CLR_BIT(TIMERS_U8_TCCR1B_REG,TIMERS_TCCR1B_WGM13);
	SET_BIT(TIMERS_U8_TCCR1B_REG,TIMERS_TCCR1B_WGM12);
	SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_WGM11);
	CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_WGM10);

#elif                TIMER1_MODE == FPWM_10_BIT_0X03FF_TOP_TOP

	CLR_BIT(TIMERS_U8_TCCR1B_REG,TIMERS_TCCR1B_WGM13);
	SET_BIT(TIMERS_U8_TCCR1B_REG,TIMERS_TCCR1B_WGM12);
	SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_WGM11);
	SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_WGM10);

#elif                TIMER1_MODE == PWM_PFC_ICR1_BOTTOM_BOTTOM

	SET_BIT(TIMERS_U8_TCCR1B_REG,TIMERS_TCCR1B_WGM13);
	CLR_BIT(TIMERS_U8_TCCR1B_REG,TIMERS_TCCR1B_WGM12);
	CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_WGM11);
	CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_WGM10);

#elif                TIMER1_MODE == PWM_PFC_OCR1A_BOTTOM_BOTTOM

	SET_BIT(TIMERS_U8_TCCR1B_REG,TIMERS_TCCR1B_WGM13);
	CLR_BIT(TIMERS_U8_TCCR1B_REG,TIMERS_TCCR1B_WGM12);
	CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_WGM11);
	SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_WGM10);


#elif                TIMER1_MODE == PWM_PC_ICR1_TOP_BOTTOM

	SET_BIT(TIMERS_U8_TCCR1B_REG,TIMERS_TCCR1B_WGM13);
	CLR_BIT(TIMERS_U8_TCCR1B_REG,TIMERS_TCCR1B_WGM12);
	SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_WGM11);
	CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_WGM10);

#elif                TIMER1_MODE == PWM_PC_OCR1A_TOP_BOTTOM

	SET_BIT(TIMERS_U8_TCCR1B_REG,TIMERS_TCCR1B_WGM13);
	CLR_BIT(TIMERS_U8_TCCR1B_REG,TIMERS_TCCR1B_WGM12);
	SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_WGM11);
	SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_WGM10);


#elif                TIMER1_MODE == CTC_ICR1_IM_MAX

	SET_BIT(TIMERS_U8_TCCR1B_REG,TIMERS_TCCR1B_WGM13);
	SET_BIT(TIMERS_U8_TCCR1B_REG,TIMERS_TCCR1B_WGM12);
	CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_WGM11);
	CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_WGM10);

#elif                TIMER1_MODE == FPWM_ICR1_TOP_TOP

	SET_BIT(TIMERS_U8_TCCR1B_REG,TIMERS_TCCR1B_WGM13);
	SET_BIT(TIMERS_U8_TCCR1B_REG,TIMERS_TCCR1B_WGM12);
	SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_WGM11);
	CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_WGM10);

#elif                TIMER1_MODE == FPWM_OCR1A_TOP_TOP

	SET_BIT(TIMERS_U8_TCCRB1_REG,TIMERS_TCCRB1_WGM13);
	SET_BIT(TIMERS_U8_TCCRB1_REG,TIMERS_TCCRB1_WGM12);
	SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_WGM11);
	SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_WGM10);

#endif


					/*Set Non-PWM Mode*/
#if                  TIMER1_MODE == NORMAL__0XFFFF_IM_MAX

						/*NON-PWM Options for OC1A*/
		#if          TIMER1_OC1A_CTC_MODE == CTC_NORMAL_MODE

			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A1);
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A0);

		#elif        TIMER1_OC1A_CTC_MODE == CTC_TOGGLE_MODE

			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A1);
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A0);

		#elif        TIMER1_OC1A_CTC_MODE == CTC_CLEAR_MODE

			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A1);
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A0);

		#elif        TIMER1_OC1A_CTC_MODE == CTC_SET_MODE

			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A1);
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A0);

		#endif

						/*NON-PWM Options for OC1B*/
		#if          TIMER1_OC1B_CTC_MODE == CTC_NORMAL_MODE

			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B1);
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B0);

		#elif        TIMER1_OC1B_CTC_MODE == CTC_TOGGLE_MODE

			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B1);
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B0);

		#elif        TIMER1_OC1B_CTC_MODE == CTC_CLEAR_MODE

			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B1);
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B0);

		#elif        TIMER1_OC1B_CTC_MODE == CTC_SET_MODE

			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B1);
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B0);

		#endif


#elif                TIMER1_MODE == CTC_OCR1A_IM_MAX
						/*NON-PWM Options for OC1A*/
		#if          TIMER1_OC1A_CTC_MODE == CTC_NORMAL_MODE

			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A1);
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A0);

		#elif        TIMER1_OC1A_CTC_MODE == CTC_TOGGLE_MODE

			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A1);
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A0);

		#elif        TIMER1_OC1A_CTC_MODE == CTC_CLEAR_MODE

			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A1);
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A0);

		#elif        TIMER1_OC1A_CTC_MODE == CTC_SET_MODE

			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A1);
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A0);

		#endif

						/*NON-PWM Options for OC1B*/
		#if          TIMER1_OC1B_CTC_MODE == CTC_NORMAL_MODE

			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B1);
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B0);

		#elif        TIMER1_OC1B_CTC_MODE == CTC_TOGGLE_MODE

			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B1);
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B0);

		#elif        TIMER1_OC1B_CTC_MODE == CTC_CLEAR_MODE

			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B1);
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B0);

		#elif        TIMER1_OC1B_CTC_MODE == CTC_SET_MODE

			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B1);
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B0);

		#endif

#elif                TIMER1_MODE == CTC_ICR1_IM_MAX

						/*NON-PWM Options for OC1A*/
		#if          TIMER1_OC1A_CTC_MODE == CTC_NORMAL_MODE

			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A1);
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A0);

		#elif        TIMER1_OC1A_CTC_MODE == CTC_TOGGLE_MODE

			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A1);
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A0);

		#elif        TIMER1_OC1A_CTC_MODE == CTC_CLEAR_MODE

			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A1);
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A0);

		#elif        TIMER1_OC1A_CTC_MODE == CTC_SET_MODE

			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A1);
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A0);

		#endif

						/*NON-PWM Options for OC1B*/
		#if          TIMER1_OC1B_CTC_MODE == CTC_NORMAL_MODE

			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B1);
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B0);

		#elif        TIMER1_OC1B_CTC_MODE == CTC_TOGGLE_MODE

			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B1);
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B0);

		#elif        TIMER1_OC1B_CTC_MODE == CTC_CLEAR_MODE

			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B1);
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B0);

		#elif        TIMER1_OC1B_CTC_MODE == CTC_SET_MODE

			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B1);
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B0);

		#endif

#endif

					/*Set Fast PWM Mode*/
#if                  TIMER1_MODE == FPWM_8_BIT_0X00FF_TOP_TOP
						/*PWM options For OC1A*/
		#if          TIMER1_OC1A_FPWM_MODE == TIMER1_FPWM_DISCONNECTED
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A1);
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A0);
		#elif        TIMER1_OC1A_FPWM_MODE == TIMER1_FPWM_TOGGLE_OC1A_MODE
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A1);
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A0);
		#elif        TIMER1_OC1A_FPWM_MODE == TIMER1_FPWM_NON_INVERTING_MODE
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A1);
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A0);
		#elif        TIMER1_OC1A_FPWM_MODE == TIMER1_FPWM_INVERTING_MODE
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A1);
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A0);
		#endif
					/*PWM Options for OC1B*/
		#if          TIMER1_OC1B_CTC_MODE == TIMER1_FPWM_DISCONNECTED

			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B1);
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B0);

		#elif        TIMER1_OC1B_CTC_MODE == TIMER1_FPWM_NON_INVERTING_MODE

			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B1);
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B0);

		#elif        TIMER1_OC1B_CTC_MODE == TIMER1_FPWM_INVERTING_MODE

			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B1);
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B0);

		#endif

#elif                TIMER1_MODE == FPWM_9_BIT_0X01FF_TOP_TOP
					  /*PWM options For OC1A*/
		#if          TIMER1_OC1A_FPWM_MODE == TIMER1_FPWM_DISCONNECTED
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A1);
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A0);
		#elif        TIMER1_OC1A_FPWM_MODE == TIMER1_FPWM_TOGGLE_OC1A_MODE
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A1);
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A0);
		#elif        TIMER1_OC1A_FPWM_MODE == TIMER1_FPWM_NON_INVERTING_MODE
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A1);
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A0);
		#elif        TIMER1_OC1A_FPWM_MODE == TIMER1_FPWM_INVERTING_MODE
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A1);
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A0);
		#endif
				/*PWM Options for OC1B*/
		#if          TIMER1_OC1B_CTC_MODE == TIMER1_FPWM_DISCONNECTED

			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B1);
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B0);

		#elif        TIMER1_OC1B_CTC_MODE == TIMER1_FPWM_NON_INVERTING_MODE

			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B1);
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B0);

		#elif        TIMER1_OC1B_CTC_MODE == TIMER1_FPWM_INVERTING_MODE

			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B1);
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B0);

		#endif

#elif                TIMER1_MODE == FPWM_10_BIT_0X03FF_TOP_TOP
					/*PWM options For OC1A*/
		#if          TIMER1_OC1A_FPWM_MODE == TIMER1_FPWM_DISCONNECTED
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A1);
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A0);
		#elif        TIMER1_OC1A_FPWM_MODE == TIMER1_FPWM_TOGGLE_OC1A_MODE
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A1);
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A0);
		#elif        TIMER1_OC1A_FPWM_MODE == TIMER1_FPWM_NON_INVERTING_MODE
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A1);
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A0);
		#elif        TIMER1_OC1A_FPWM_MODE == TIMER1_FPWM_INVERTING_MODE
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A1);
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A0);
		#endif
					/*PWM Options for OC1B*/
		#if          TIMER1_OC1B_CTC_MODE == TIMER1_FPWM_DISCONNECTED

			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B1);
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B0);

		#elif        TIMER1_OC1B_CTC_MODE == TIMER1_FPWM_NON_INVERTING_MODE

			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B1);
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B0);

		#elif        TIMER1_OC1B_CTC_MODE == TIMER1_FPWM_INVERTING_MODE

			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B1);
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B0);

		#endif
#elif                TIMER1_MODE == FPWM_ICR1_TOP_TOP
					/*PWM options For OC1A*/
		#if          TIMER1_OC1A_FPWM_MODE == TIMER1_FPWM_DISCONNECTED
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A1);
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A0);
		#elif        TIMER1_OC1A_FPWM_MODE == TIMER1_FPWM_TOGGLE_OC1A_MODE
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A1);
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A0);
		#elif        TIMER1_OC1A_FPWM_MODE == TIMER1_FPWM_NON_INVERTING_MODE
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A1);
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A0);
		#elif        TIMER1_OC1A_FPWM_MODE == TIMER1_FPWM_INVERTING_MODE
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A1);
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A0);
		#endif
				/*PWM Options for OC1B*/
		#if          TIMER1_OC1B_CTC_MODE == TIMER1_FPWM_DISCONNECTED

			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B1);
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B0);

		#elif        TIMER1_OC1B_CTC_MODE == TIMER1_FPWM_NON_INVERTING_MODE

			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B1);
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B0);

		#elif        TIMER1_OC1B_CTC_MODE == TIMER1_FPWM_INVERTING_MODE

			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B1);
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B0);

		#endif
#elif                TIMER1_MODE == FPWM_OCR1A_TOP_TOP

					/*PWM options For OC1A*/
		#if          TIMER1_OC1A_FPWM_MODE == TIMER1_FPWM_DISCONNECTED
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A1);
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A0);
		#elif          TIMER1_OC1A_FPWM_MODE == TIMER1_FPWM_TOGGLE_OC1A_MODE
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A1);
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A0);
		#elif        TIMER1_OC1A_FPWM_MODE == TIMER1_FPWM_NON_INVERTING_MODE
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A1);
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A0);
		#elif        TIMER1_OC1A_FPWM_MODE == TIMER1_FPWM_INVERTING_MODE
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A1);
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A0);
		#endif
				/*PWM Options for OC1B*/
		#if          TIMER1_OC1B_CTC_MODE == TIMER1_FPWM_DISCONNECTED

			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B1);
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B0);

		#elif        TIMER1_OC1B_CTC_MODE == TIMER1_FPWM_NON_INVERTING_MODE

			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B1);
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B0);

		#elif        TIMER1_OC1B_CTC_MODE == TIMER1_FPWM_INVERTING_MODE

			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B1);
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B0);

		#endif

#endif
				/*Set Phase Correct PWM Mode*/
#if                  TIMER1_MODE == PWM_PC_8_BIT_0X00FF_TOP_BOTTOM

			   /* Phase Correct PWM options For OC1A*/
		#if          TIMER1_OC1A_PC_PWM_MODE == TIMER1_PC_PWM_DISCONNECTED
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A1);
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A0);

		#elif        TIMER1_OC1A_PC_PWM_MODE == TIMER1_PC_PWM_TOGGLE_OC1A_MODE_MODE
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A1);
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A0);
		#elif        TIMER1_OC1A_PC_PWM_MODE == TIMER1_PC_PWM_NON_INVERTING_MODE
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A1);
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A0);
		#elif		 TIMER1_OC1A_PC_PWM_MODE == TIMER1_PC_PWM_INVERTING_MODE
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A1);
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A0);
		#endif

			/* Phase Correct PWM options For OC1B*/
		#if          TIMER1_OC1B_PC_PWM_MODE == TIMER1_PC_PWM_DISCONNECTED
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B1);
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B0);
		#elif        TIMER1_OC1B_PC_PWM_MODE == TIMER1_PC_PWM_NON_INVERTING_MODE
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B1);
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B0);
		#elif        TIMER1_OC1B_PC_PWM_MODE == TIMER1_PC_PWM_INVERTING_MODE
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B1);
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B0);
		#endif



#elif                TIMER1_MODE == PWM_PC_9_BIT_0X01FF_TOP_BOTTOM

			   /* Phase Correct PWM options For OC1A*/
		#if          TIMER1_OC1A_PC_PWM_MODE == TIMER1_PC_PWM_DISCONNECTED
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A1);
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A0);

		#elif        TIMER1_OC1A_PC_PWM_MODE == TIMER1_PC_PWM_TOGGLE_OC1A_MODE_MODE
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A1);
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A0);
		#elif        TIMER1_OC1A_PC_PWM_MODE == TIMER1_PC_PWM_NON_INVERTING_MODE
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A1);
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A0);
		#elif		 TIMER1_OC1A_PC_PWM_MODE == TIMER1_PC_PWM_INVERTING_MODE
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A1);
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A0);
		#endif

			/* Phase Correct PWM options For OC1B*/
		#if          TIMER1_OC1B_PC_PWM_MODE == TIMER1_PC_PWM_DISCONNECTED
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B1);
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B0);
		#elif        TIMER1_OC1B_PC_PWM_MODE == TIMER1_PC_PWM_NON_INVERTING_MODE
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B1);
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B0);
		#elif        TIMER1_OC1B_PC_PWM_MODE == TIMER1_PC_PWM_INVERTING_MODE
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B1);
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B0);
		#endif


#elif                TIMER1_MODE == PWM_PC_10_BIT_0X03FF_TOP_BOTTOM

			   /* Phase Correct PWM options For OC1A*/
		#if          TIMER1_OC1A_PC_PWM_MODE == TIMER1_PC_PWM_DISCONNECTED
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A1);
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A0);

		#elif        TIMER1_OC1A_PC_PWM_MODE == TIMER1_PC_PWM_TOGGLE_OC1A_MODE_MODE
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A1);
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A0);
		#elif        TIMER1_OC1A_PC_PWM_MODE == TIMER1_PC_PWM_NON_INVERTING_MODE
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A1);
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A0);
		#elif		 TIMER1_OC1A_PC_PWM_MODE == TIMER1_PC_PWM_INVERTING_MODE
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A1);
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A0);
		#endif

			/* Phase Correct PWM options For OC1B*/
		#if          TIMER1_OC1B_PC_PWM_MODE == TIMER1_PC_PWM_DISCONNECTED
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B1);
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B0);
		#elif        TIMER1_OC1B_PC_PWM_MODE == TIMER1_PC_PWM_NON_INVERTING_MODE
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B1);
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B0);
		#elif        TIMER1_OC1B_PC_PWM_MODE == TIMER1_PC_PWM_INVERTING_MODE
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B1);
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B0);
		#endif

#elif                TIMER1_MODE == PWM_PFC_ICR1_BOTTOM_BOTTOM

			   /* Phase Correct PWM options For OC1A*/
		#if          TIMER1_OC1A_PC_PWM_MODE == TIMER1_PC_PWM_DISCONNECTED
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A1);
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A0);

		#elif        TIMER1_OC1A_PC_PWM_MODE == TIMER1_PC_PWM_TOGGLE_OC1A_MODE_MODE
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A1);
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A0);
		#elif        TIMER1_OC1A_PC_PWM_MODE == TIMER1_PC_PWM_NON_INVERTING_MODE
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A1);
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A0);
		#elif		 TIMER1_OC1A_PC_PWM_MODE == TIMER1_PC_PWM_INVERTING_MODE
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A1);
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A0);
		#endif

			/* Phase Correct PWM options For OC1B*/
		#if          TIMER1_OC1B_PC_PWM_MODE == TIMER1_PC_PWM_DISCONNECTED
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B1);
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B0);
		#elif        TIMER1_OC1B_PC_PWM_MODE == TIMER1_PC_PWM_NON_INVERTING_MODE
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B1);
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B0);
		#elif        TIMER1_OC1B_PC_PWM_MODE == TIMER1_PC_PWM_INVERTING_MODE
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B1);
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B0);
		#endif
#elif                TIMER1_MODE == PWM_PFC_OCR1A_BOTTOM_BOTTOM

			   /* Phase Correct PWM options For OC1A*/
		#if          TIMER1_OC1A_PC_PWM_MODE == TIMER1_PC_PWM_DISCONNECTED
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A1);
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A0);

		#elif        TIMER1_OC1A_PC_PWM_MODE == TIMER1_PC_PWM_TOGGLE_OC1A_MODE_MODE
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A1);
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A0);
		#elif        TIMER1_OC1A_PC_PWM_MODE == TIMER1_PC_PWM_NON_INVERTING_MODE
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A1);
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A0);
		#elif		 TIMER1_OC1A_PC_PWM_MODE == TIMER1_PC_PWM_INVERTING_MODE
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A1);
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A0);
		#endif

			/* Phase Correct PWM options For OC1B*/
		#if          TIMER1_OC1B_PC_PWM_MODE == TIMER1_PC_PWM_DISCONNECTED
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B1);
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B0);
		#elif        TIMER1_OC1B_PC_PWM_MODE == TIMER1_PC_PWM_NON_INVERTING_MODE
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B1);
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B0);
		#elif        TIMER1_OC1B_PC_PWM_MODE == TIMER1_PC_PWM_INVERTING_MODE
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B1);
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B0);
		#endif
#elif                TIMER1_MODE == PWM_PC_ICR1_TOP_BOTTOM

			   /* Phase Correct PWM options For OC1A*/
		#if          TIMER1_OC1A_PC_PWM_MODE == TIMER1_PC_PWM_DISCONNECTED
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A1);
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A0);

		#elif        TIMER1_OC1A_PC_PWM_MODE == TIMER1_PC_PWM_TOGGLE_OC1A_MODE_MODE
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A1);
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A0);
		#elif        TIMER1_OC1A_PC_PWM_MODE == TIMER1_PC_PWM_NON_INVERTING_MODE
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A1);
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A0);
		#elif		 TIMER1_OC1A_PC_PWM_MODE == TIMER1_PC_PWM_INVERTING_MODE
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A1);
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A0);
		#endif

			/* Phase Correct PWM options For OC1B*/
		#if          TIMER1_OC1B_PC_PWM_MODE == TIMER1_PC_PWM_DISCONNECTED
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B1);
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B0);
		#elif        TIMER1_OC1B_PC_PWM_MODE == TIMER1_PC_PWM_NON_INVERTING_MODE
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B1);
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B0);
		#elif        TIMER1_OC1B_PC_PWM_MODE == TIMER1_PC_PWM_INVERTING_MODE
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B1);
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B0);
		#endif
#elif                TIMER1_MODE == PWM_PC_OCR1A_TOP_BOTTOM

			   /* Phase Correct PWM options For OC1A*/
		#if          TIMER1_OC1A_PC_PWM_MODE == TIMER1_PC_PWM_DISCONNECTED
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A1);
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A0);

		#elif        TIMER1_OC1A_PC_PWM_MODE == TIMER1_PC_PWM_TOGGLE_OC1A_MODE_MODE
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A1);
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A0);
		#elif        TIMER1_OC1A_PC_PWM_MODE == TIMER1_PC_PWM_NON_INVERTING_MODE
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A1);
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A0);
		#elif		 TIMER1_OC1A_PC_PWM_MODE == TIMER1_PC_PWM_INVERTING_MODE
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A1);
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1A0);
		#endif

			/* Phase Correct PWM options For OC1B*/
		#if          TIMER1_OC1B_PC_PWM_MODE == TIMER1_PC_PWM_DISCONNECTED
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B1);
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B0);
		#elif        TIMER1_OC1B_PC_PWM_MODE == TIMER1_PC_PWM_NON_INVERTING_MODE
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B1);
			CLR_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B0);
		#elif        TIMER1_OC1B_PC_PWM_MODE == TIMER1_PC_PWM_INVERTING_MODE
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B1);
			SET_BIT(TIMERS_U8_TCCR1A_REG,TIMERS_TCCR1A_COM1B0);
		#endif

#endif
			/*Update Value to ICR1*/
			TIMERS_U16_ICR1_REG =  TIMER1_MAX_OVF_VALUE ;
			/*Update value to OCR1A*/
			TIMERS_U16_OCR1A_REG = TIMER1_CTC_OC1A_VALUE;
			/*Update value to OCR1B*/
			TIMERS_U16_OCR1B_REG = TIMER1_CTC_OC1B_VALUE;


            /*Set preScaler*/
#if                  TIMER1_PRESCALER_MODE  == TIMER_OFF

	CLR_BIT (TIMERS_U8_TCCR1B_REG,TIMERS_TCCR1B_CS10);
	CLR_BIT (TIMERS_U8_TCCR1B_REG,TIMERS_TCCR1B_CS11);
	CLR_BIT (TIMERS_U8_TCCR1B_REG,TIMERS_TCCR1B_CS12);

#elif                TIMER1_PRESCALER_MODE  == DIVIDED_BY_1

	SET_BIT (TIMERS_U8_TCCR1B_REG,TIMERS_TCCR1B_CS10);
	CLR_BIT (TIMERS_U8_TCCR1B_REG,TIMERS_TCCR1B_CS11);
	CLR_BIT (TIMERS_U8_TCCR1B_REG,TIMERS_TCCR1B_CS12);

#elif                TIMER1_PRESCALER_MODE  == DIVIDED_BY_8

	CLR_BIT (TIMERS_U8_TCCR1B_REG,TIMERS_TCCR1B_CS10);
	SET_BIT (TIMERS_U8_TCCR1B_REG,TIMERS_TCCR1B_CS11);
	CLR_BIT (TIMERS_U8_TCCR1B_REG,TIMERS_TCCR1B_CS12);

#elif                TIMER1_PRESCALER_MODE  == DIVIDED_BY_64

	SET_BIT (TIMERS_U8_TCCR1B_REG,TIMERS_TCCR1B_CS10);
	SET_BIT (TIMERS_U8_TCCR1B_REG,TIMERS_TCCR1B_CS11);
	CLR_BIT (TIMERS_U8_TCCR1B_REG,TIMERS_TCCR1B_CS12);

#elif                TIMER1_PRESCALER_MODE  == DIVIDED_BY_256

	CLR_BIT (TIMERS_U8_TCCR1B_REG,TIMERS_TCCR1B_CS10);
	CLR_BIT (TIMERS_U8_TCCR1B_REG,TIMERS_TCCR1B_CS11);
	SET_BIT (TIMERS_U8_TCCR1B_REG,TIMERS_TCCR1B_CS12);


#elif                TIMER1_PRESCALER_MODE  == DIVIDED_BY_1024

	SET_BIT (TIMERS_U8_TCCR1B_REG,TIMERS_TCCR1B_CS10);
	CLR_BIT (TIMERS_U8_TCCR1B_REG,TIMERS_TCCR1B_CS11);
	SET_BIT (TIMERS_U8_TCCR1B_REG,TIMERS_TCCR1B_CS12);

#elif                TIMER1_PRESCALER_MODE  == T1_FALLING

	CLR_BIT (TIMERS_U8_TCCR1B_REG,TIMERS_TCCR1B_CS10);
	SET_BIT (TIMERS_U8_TCCR1B_REG,TIMERS_TCCR1B_CS11);
	SET_BIT (TIMERS_U8_TCCR1B_REG,TIMERS_TCCR1B_CS12);

#elif                TIMER1_PRESCALER_MODE  == T1_RISING

	SET_BIT (TIMERS_U8_TCCR1B_REG,TIMERS_TCCR1B_CS10);
	SET_BIT (TIMERS_U8_TCCR1B_REG,TIMERS_TCCR1B_CS11);
	SET_BIT (TIMERS_U8_TCCR1B_REG,TIMERS_TCCR1B_CS12);

#endif


}








/**************************************Prototype for ISR of TIMER0 OverFlow***************************/
void __vector_11 (void) __attribute__((signal));
void __vector_11 (void)
{
	static u16 Locale_u16CounterOVF = 0;


	Locale_u16CounterOVF++;
	if (Locale_u16CounterOVF == TIMER0_OVF_REQ_NO)
	{
		/*Update preLoad value*/
		TIMERS_U8_TCNT0_REG = TIMER0_PRELOAD;
		/*Clear OverFlow Counter*/
		Locale_u16CounterOVF = 0;
		/*Call App Function*/
		if (TIMERS_pfTimer0OVF != NULL)
		{
			TIMERS_pfTimer0OVF();
		}
	}
}
/*****************************************************************************************************/

/**************************************Prototype for ISR of TIMER0 CTC *******************************/

void __vector_10 (void) __attribute__((signal));
void __vector_10 (void)
{

	static u16 Local_u16CounterCTC = 0;

	Local_u16CounterCTC++;

	if (Local_u16CounterCTC == TIMER0_CTC_REQ_NO)
	{
		/*Clear CTC Counter*/
		Local_u16CounterCTC = 0;
		/*Call App Function*/
		if (TIMERS_pfTimer0CTC != NULL)
		{
			TIMERS_pfTimer0CTC();
		}
	}
}
/*****************************************************************************************************/



#endif
